const {chromium}=require('playwright');const assert=require('node:assert/strict');
const path=require('node:path');const fs=require('node:fs');const gra=path.resolve(__dirname,'..');const base=path.join(gra,'test-results');fs.mkdirSync(base,{recursive:true});
(async()=>{const {createServer}=await import(path.join(gra,'node_modules/vite/dist/node/index.js'));const server=await createServer({configFile:path.join(gra,'vite.config.js'),root:path.join(gra,'src'),server:{host:'127.0.0.1',port:5173}});await server.listen();const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
let page;try{
page=await browser.newPage({viewport:{width:1100,height:800},deviceScaleFactor:.75});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>window.__farm);
const state=()=>page.evaluate(()=>window.__farm.state());
const places={house:[-3,1.5],forest:[-7,-1.3],mine:[5.5,-3.3],garden:[-2.8,5.5],pen:[3,4.8],shop:[-7,2.6],land:[9,5.8]};
async function go(id){await page.getByRole('button',{name:'Pokaż całą farmę',exact:true}).click();await page.waitForTimeout(1000);await page.locator(`[data-place="${id}"]`).click();await page.waitForFunction(([x,z])=>{const p=window.__farm.inspect().position;return Math.hypot(p[0]-x,p[2]-z)<.8;},places[id],{timeout:90000});await page.waitForTimeout(250);console.log('arrived',id);}
async function act(label){await page.getByRole('button',{name:label,exact:true}).click();await page.waitForTimeout(1400);}
await go('forest');await act('Zbierz drewno');assert.equal((await state()).wood,6);
await go('mine');await act('Wydobądź kamień');assert.equal((await state()).stone,5);
await go('house');await act('Zbuduj dom');assert.equal((await state()).houseLevel,1);assert.equal((await state()).wood,0);console.log('PASS fresh save gathering and house construction');
await go('shop');await act('Otwórz sklepik');await page.locator('[data-action="buy-seeds"]').click();assert.equal((await state()).seeds,1);assert.equal((await state()).coins,6);assert.match(await page.locator('.shop-feedback').innerText(),/Kupiono/);await page.getByRole('button',{name:'Zamknij',exact:true}).click();
await go('garden');await act('Posiej marchewki');await act('Podlej ogród');await act('Zbierz marchewki');assert.equal((await state()).carrots,3);console.log('PASS shop purchase and complete crop cycle');
// A fixture moves this same browser into a progressed save to cover the later stage without repetitive gathering.
await page.evaluate(()=>localStorage.setItem('eklamerka-world-v1',JSON.stringify({...window.__farm.state(),wood:100,stone:100,coins:18,carrots:6,pen:true,rabbits:true,babies:1,name:'Kaja'})));await page.reload();await page.waitForFunction(()=>window.__farm);
const before=await page.evaluate(()=>window.__farm.inspect());await page.keyboard.down('w');await page.waitForTimeout(320);const walking=await page.evaluate(()=>window.__farm.inspect());await page.keyboard.up('w');assert.notDeepEqual(before.position,walking.position);assert(walking.joints.some(v=>Math.abs(v)>.03));await page.waitForTimeout(1200);const after=await page.evaluate(()=>window.__farm.inspect());assert.notDeepEqual(before.rabbits,after.rabbits);console.log('PASS articulated walk and independently animated rabbits');
await go('house');const uuid1=await page.evaluate(()=>window.__farm.inspect().objects.house);await act('Rozbuduj dom');assert.equal((await state()).houseLevel,2);const uuid2=await page.evaluate(()=>window.__farm.inspect().objects.house);assert.notEqual(uuid1,uuid2);await act('Rozbuduj dom');assert.equal((await state()).houseLevel,3);console.log('PASS house replaces its real geometry at each level');
await go('pen');await act('Nakarm króliczki');assert.equal((await state()).carrots,4);assert((await state()).nextBirthAt>Date.now());assert.equal(await page.getByRole('button',{name:'Nakarm króliczki',exact:true}).isDisabled(),true);
// Simulate returning after a due pregnancy, through the same persisted state read used on real reloads.
await page.evaluate(()=>localStorage.setItem('eklamerka-world-v1',JSON.stringify({...window.__farm.state(),nextBirthAt:Date.now()-1000})));await page.reload();await page.waitForFunction(()=>window.__farm?.state().babies===2);assert.equal((await state()).carrots,4);console.log('PASS birth survives reload without a second food charge');
await go('shop');await act('Otwórz sklepik');const coins=(await state()).coins;await page.locator('[data-action="sell-baby"]').click();assert.equal((await state()).coins,coins+5);assert.equal((await state()).babies,1);assert.match(await page.locator('.shop-feedback').innerText(),/\+5/);assert.equal(await page.locator('.modal [data-resource="coins"]').innerText(),String(coins+5));await page.screenshot({path:base+'/3d-shop-tested.png'});await page.getByRole('button',{name:'Zamknij',exact:true}).click();await page.reload();await page.waitForFunction(()=>window.__farm);assert.equal((await state()).coins,coins+5);console.log('PASS sale updates both visible balance and persisted save');
await go('land');await act('Powiększ farmę');assert.equal((await state()).landLevel,1);await page.getByRole('button',{name:'Pokaż całą farmę',exact:true}).click();await page.waitForTimeout(1000);await page.screenshot({path:base+'/e-klamerka-3d-desktop.png'});assert.deepEqual(errors,[]);console.log('PASS land expansion and no runtime errors');
// Mobile pointer movement and dialog layout.
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});mobile.on('pageerror',e=>errors.push(e.message));await mobile.addInitScript(()=>localStorage.setItem('eklamerka-world-v1',JSON.stringify({version:1,name:'Tola',houseLevel:2,pen:true,rabbits:true,babies:2,wood:12,stone:8,coins:18,carrots:6,seeds:2,planted:true,watered:true})));await mobile.goto('http://127.0.0.1:5173');await mobile.waitForFunction(()=>window.__farm);const mBefore=await mobile.evaluate(()=>window.__farm.inspect().position);const j=await mobile.locator('.joystick').boundingBox();await mobile.mouse.move(j.x+j.width/2,j.y+j.height/2);await mobile.mouse.down();await mobile.mouse.move(j.x+j.width/2+30,j.y+j.height/2-15);await mobile.waitForTimeout(900);await mobile.mouse.up();const mAfter=await mobile.evaluate(()=>window.__farm.inspect().position);assert.notDeepEqual(mBefore,mAfter);await mobile.waitForTimeout(150);assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await mobile.screenshot({path:base+'/e-klamerka-3d-mobile.png'});console.log('PASS mobile joystick pointermove, no horizontal overflow');await mobile.close();
console.log('ALL E2E CHECKS PASSED');
}catch(e){console.error(e);if(page){console.log('DEBUG',await page.evaluate(()=>window.__farm?.inspect()).catch(()=>null));await page.screenshot({path:base+'/e2e-failure.png'}).catch(()=>{});}process.exitCode=1;}finally{await browser.close();await server.close();}
})();
