const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');const fs=require('node:fs');
const gra=path.resolve(__dirname,'..'),output=path.join(gra,'test-results');fs.mkdirSync(output,{recursive:true});
(async()=>{const {createServer}=await import(path.join(gra,'node_modules/vite/dist/node/index.js'));const server=await createServer({configFile:path.join(gra,'vite.config.js'),root:path.join(gra,'src'),server:{host:'127.0.0.1',port:5173}});await server.listen();const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});const errors=[];
try{
const page=await browser.newPage({viewport:{width:1000,height:760},deviceScaleFactor:.75});page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{if(!localStorage.getItem('eklamerka-world-v1'))localStorage.setItem('eklamerka-world-v1',JSON.stringify({version:1,name:'Kaja',houseLevel:2,pen:true,rabbits:true,babies:2,wood:50,stone:40,coins:30,carrots:8,seeds:4,crystals:8,planted:true,watered:true,world:{quarry:true,meadow:true,orchard:true,windmill:true,visited:['farm','woodland','quarry','meadow']}}));});
await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>window.__farm);
console.log('READY',await page.evaluate(()=>({fps:window.__farm.inspect().fps,draws:window.__farm.inspect().calls})));
const routes=await page.evaluate(()=>[[-29,1],[0,-27],[28,2],[33,-1.5]].map(p=>({to:p,path:window.__farm.inspect().routeTo(...p)})));for(const r of routes){assert(r.path.length>0,`no route to ${r.to}`);assert(Math.hypot(r.path.at(-1)[0]-r.to[0],r.path.at(-1)[2]-r.to[1])<.6);}console.log('PASS actual scene collisions allow routes into all regions');
await page.getByRole('button',{name:'Otwórz mapę świata'}).click();await page.screenshot({path:path.join(output,'world-map.png')});assert.equal(await page.locator('.map-node').count(),4);await page.getByRole('button',{name:'Obejrzyj cały świat'}).click();await page.waitForTimeout(1600);await page.screenshot({path:path.join(output,'world-overview.png')});
await page.getByRole('button',{name:'Otwórz mapę świata'}).click();await page.locator('[data-region="woodland"]').click();await page.waitForTimeout(500);assert((await page.evaluate(()=>window.__farm.inspect().routeLength))>20);console.log('PASS map selects a real walking route, without teleporting');await page.getByRole('button',{name:'Zatrzymaj',exact:true}).click();
// A mobile context tests native touch input, including no accidental walking after a two-finger gesture.
const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto('http://127.0.0.1:5173');await mobile.waitForFunction(()=>window.__farm);assert.equal(await mobile.locator('.joystick').count(),0);
const touch=await mobile.context().newCDPSession(mobile),send=(type,points)=>touch.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(([x,y,id])=>({x,y,id,radiusX:6,radiusY:6,force:1}))});
const start=await mobile.evaluate(()=>window.__farm.inspect().position);const goal=await mobile.evaluate(()=>window.__farm.inspect().project([1.8,0,5]));
await send('touchStart',[[goal.x-30,goal.y+25,0]]);await send('touchMove',[[goal.x,goal.y,0]]);await send('touchEnd',[]);await mobile.waitForTimeout(1800);
const moved=await mobile.evaluate(()=>window.__farm.inspect().position);assert.notDeepEqual(start,moved);console.log('PASS one-finger screen drag moves the character');
const camBefore=await mobile.evaluate(()=>window.__farm.inspect().camera);
await send('touchStart',[[140,390,0],[235,390,1]]);await send('touchMove',[[115,420,0],[267,357,1]]);await send('touchEnd',[]);const camAfter=await mobile.evaluate(()=>window.__farm.inspect().camera);assert(Math.abs(camBefore.zoom-camAfter.zoom)>.1);assert(Math.abs(camBefore.yaw-camAfter.yaw)>.1);assert.equal(await mobile.evaluate(()=>window.__farm.inspect().routeLength),0);console.log('PASS pinch and rotation, with no spurious tap after multi-touch');
await mobile.getByRole('button',{name:'Otwórz mapę świata'}).click();await mobile.screenshot({path:path.join(output,'world-map-mobile.png')});assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await mobile.getByRole('button',{name:'Zamknij',exact:true}).click();await mobile.screenshot({path:path.join(output,'gestures-mobile.png')});await mobile.close();
await page.setViewportSize({width:1440,height:960});await page.getByRole('button',{name:'Otwórz mapę świata'}).click();await page.getByRole('button',{name:'Obejrzyj cały świat'}).click();await page.waitForTimeout(900);await page.screenshot({path:path.join(output,'world-overview-large.png')});assert.deepEqual(errors,[]);console.log('ALL WORLD AND GESTURE CHECKS PASSED');
}catch(e){console.error(e);process.exitCode=1;}finally{await browser.close();await server.close();}
})();
