import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const initial = { name: '', avatar: 'girl', wood: 4, stone: 3, carrots: 2, coins: 8, house: false, hutch: false, planted: false, watered: false, rabbits: 0, fed: false, chapter: 0 };
const readSave = () => { try { return { ...initial, ...JSON.parse(localStorage.getItem('ek-save') || '{}') }; } catch { return initial; } };
function Village({onToast}) {
  const [joined,setJoined] = useState(false);
  const [invite,setInvite] = useState(false);
  return <div className="village-view"><section className="hero village-hero"><div><p className="eyebrow">WSPÓLNIE RAŹNIEJ</p><h1>Wioska<br/><em>Przyjaciół</em></h1><p className="intro">Połącz siły z innymi farmami. Razem zbudujecie coś wielkiego!</p></div><div className="hero-bunny">🏘️</div></section><section className="quest-card"><div className="section-heading"><div><span className="eyebrow">WSPÓLNE ZADANIE</span><h2>Budujemy most do łąki!</h2></div><span className="sparkle">🌉</span></div><p className="village-desc">Każda osoba może dorzucić trochę drewna. Wspólnymi siłami otworzycie nowy zakątek mapy.</p><div className="village-progress"><div><span>🪵 Zebrane deski</span><b>{joined?'7':'4'} / 12</b></div><div className="progress-track"><i style={{width:joined?'58%':'33%'}}/></div></div><button className="primary-wide" onClick={()=>{setJoined(true);onToast('Dorzuciłaś 3 deski do wspólnego mostu!')}}>{joined?'✓ Dołożyłaś już deski':'🪵 Dołóż 3 deski'}</button></section><section className="actions-card"><div className="section-heading"><div><span className="eyebrow">SĄSIEDNIE FARMY</span><h2>Poznaj sąsiadów</h2></div><span className="sparkle">👋</span></div><div className="neighbor-row"><span className="neighbor-avatar">👧🏻</span><div><b>Farma Jagódek</b><small>Ola · uprawia truskawki</small></div><button onClick={()=>onToast('Wizyta u sąsiadów będzie dostępna w kolejnym teście.')}>Odwiedź</button></div><div className="neighbor-row"><span className="neighbor-avatar">👦🏽</span><div><b>Zielone Wzgórze</b><small>Maks · hoduje kurki</small></div><button onClick={()=>onToast('Wizyta u sąsiadów będzie dostępna w kolejnym teście.')}>Odwiedź</button></div><button className="outline-wide" onClick={()=>setInvite(!invite)}>{invite?'Link zaproszenia skopiowany!':'＋ Zaproś znajomego'}</button>{invite&&<p className="invite-note">W prawdziwej grze zaproszenia będą działać przez prywatny link od rodzica.</p>}</section><section className="safety-note"><span>🛡️</span><div><b>Bezpieczna zabawa</b><p>Na początek gramy z zaproszonymi osobami. Bez publicznego czatu, danych osobowych i wiadomości od nieznajomych.</p></div></section></div>;
}

function App() {
  const [game, setGame] = useState(readSave);
  const [toast, setToast] = useState('');
  const [showName, setShowName] = useState(!readSave().name);
  const [newAvatar, setNewAvatar] = useState(readSave().avatar || 'girl');
  const [tab, setTab] = useState('farma');
  const [showShop, setShowShop] = useState(false);
  useEffect(() => { localStorage.setItem('ek-save', JSON.stringify(game)); }, [game]);
  useEffect(() => { if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(() => {}); }, []);
  const act = (key, delta, message, test = () => true, extra = {}) => {
    if (!test(game)) { say('Jeszcze nie teraz — wykonaj wcześniejsze zadania!'); return; }
    setGame(g => ({ ...g, [key]: typeof delta === 'function' ? delta(g[key]) : g[key] + delta, ...extra })); say(message);
  };
  const say = (s) => { setToast(s); window.clearTimeout(window._ekToast); window._ekToast = window.setTimeout(() => setToast(''), 2100); };
  const chores = [
    ['Zbierz drewno', game.wood >= 6], ['Zbierz kamień', game.stone >= 5], ['Zbuduj domek', game.house], ['Zasadź marchewki', game.planted], ['Przygotuj zagrodę', game.hutch], ['Poznaj króliki', game.rabbits >= 2]
  ];
  const done = chores.filter(x => x[1]).length;
  const buyHouse = () => { if (game.wood < 6 || game.stone < 5) return say('Potrzebujesz 6 drewna i 5 kamieni. Zbierz je na polanie!'); setGame(g=>({...g,wood:g.wood-6,stone:g.stone-5,house:true,chapter:1})); say('Hurra! Domek gotowy!'); };
  const buyHutch = () => { if(!game.house) return say('Najpierw zbuduj domek.'); if(game.wood<3||game.coins<3) return say('Zagroda kosztuje 3 drewna i 3 monety.'); setGame(g=>({...g,wood:g.wood-3,coins:g.coins-3,hutch:true})); say('Zagroda jest gotowa na nowych przyjaciół!'); };
  const plant = () => { if(!game.house) return say('Najpierw zbuduj domek.'); if(game.carrots<1) return say('Brakuje nasionek marchewki.'); setGame(g=>({...g,carrots:g.carrots-1,planted:true,watered:false})); say('Posadzone! Podlej grządkę.'); };
  const water = () => { if(!game.planted) return say('Najpierw posadź marchewki.'); if(game.watered) return say('Grządka już podlana.'); setGame(g=>({...g,watered:true,carrots:g.carrots+2,coins:g.coins+2})); say('Urosły marchewki! +2 marchewki, +2 monety'); };
  const meetBunnies = () => { if(!game.hutch) return say('Najpierw zbuduj bezpieczną zagrodę.'); if(game.rabbits) return say('Bezuch i Karmelka już są u siebie!'); setGame(g=>({...g,rabbits:2})); say('Poznaj Bezucha i Karmelkę!'); };
  const feed = () => { if(game.rabbits<2) return say('Najpierw przywitaj króliki.'); if(game.carrots<1) return say('Króliki zgłodniały — zbierz marchewki!'); if(game.fed) return say('Króliki są najedzone i zadowolone.'); setGame(g=>({...g,carrots:g.carrots-1,fed:true,coins:g.coins+3})); say('Króliki najedzone! Sklepik kupił dodatkowe plony. +3 monety'); };
  const shopSell = () => { if(game.carrots<3) return say('Zbierz jeszcze marchewki — potrzeba 3.'); setGame(g=>({...g,carrots:g.carrots-3,coins:g.coins+4})); say('Sprzedane! +4 monety'); };
  const shopSeeds = () => { if(game.coins<2) return say('Potrzebujesz 2 monet na paczkę nasion.'); setGame(g=>({...g,coins:g.coins-2,carrots:g.carrots+2})); say('Kupiono 2 nasionka marchewki!'); };
  const shopMaterials = () => { if(game.coins<5) return say('Potrzebujesz 5 monet na pakiet materiałów.'); setGame(g=>({...g,coins:g.coins-5,wood:g.wood+2,stone:g.stone+2})); say('Pakiet materiałów dodany: +2 drewna i +2 kamienie.'); };
  const submitName = (e) => { e.preventDefault(); const n = new FormData(e.currentTarget).get('name').trim().slice(0,16); if(n) { setGame(g=>({...g,name:n,avatar:newAvatar})); setShowName(false); say(`Witaj na farmie, ${n}!`); } };
  const reset = () => { if(confirm('Zacząć od nowa? Skasujesz zapis tej farmy na tym urządzeniu.')) { localStorage.removeItem('ek-save'); setGame(initial); setShowName(true); } };
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">⌁</span><span><b>E‑Klamerka</b><small>moja mała farma</small></span></div><button className="avatar" aria-label="Twoja postać" onClick={()=>say(`Cześć, ${game.name||'farmerze'}!`)}>{game.avatar==='boy'?'👦🏻‍🌾':'👧🏻‍🌾'}</button></header>
    <nav className="main-tabs"><button className={tab==='farma'?'active':''} onClick={()=>setTab('farma')}>🌱 Moja farma</button><button className={tab==='wioska'?'active':''} onClick={()=>setTab('wioska')}>🏘️ Wioska <span className="soon-dot">NOWE</span></button></nav>
    {tab==='farma'? <><section className="hero"><div><p className="eyebrow">WITAJ NA FARMIE{game.name ? `, ${game.name.toUpperCase()}` : ''}!</p><h1>Mały domek,<br/><em>wielkie przygody.</em></h1><p className="intro">Zbieraj, buduj i opiekuj się królikami. To Twoje miejsce — urządzaj je po swojemu!</p></div><div className="hero-bunny" aria-hidden="true">🐰</div></section>
    <section className="stats" aria-label="Twoje zasoby"><div className="stat"><span>🪵</span><b>{game.wood}</b><small>drewno</small></div><div className="stat"><span>🪨</span><b>{game.stone}</b><small>kamień</small></div><div className="stat"><span>🥕</span><b>{game.carrots}</b><small>marchewki</small></div><div className="stat"><span>🪙</span><b>{game.coins}</b><small>monety</small></div></section>
    <section className="scene-card"><div className="scene-title"><div><span className="eyebrow">TWOJA DZIAŁKA</span><h2>Polana pod Lasem</h2></div><span className="sun">☀️</span></div><div className="world" role="img" aria-label="Ilustracja farmy z domkiem, grządką i królikami"><div className="cloud c1">☁️</div><div className="cloud c2">☁️</div><div className="hill hill-a"></div><div className="hill hill-b"></div><div className="tree tree-a">🌳</div><div className="tree tree-b">🌲</div><div className="path"></div>{game.house?<div className="house"><div className="roof"></div><div className="walls"><span className="window">▦</span><span className="door">▮</span></div></div>:<div className="build-spot">🏗️<small>tu stanie domek</small></div>}{game.planted&&<div className="garden">{game.watered?'🥕 🥕 🥕':'🌱 🌱 🌱'}<small>grządka</small></div>}{game.hutch&&<div className="hutch">🛖<small>zagroda</small></div>}{game.rabbits>0&&<div className="bunny b1">🐇</div>}{game.rabbits>1&&<div className="bunny b2">🐰</div>}</div><div className="scene-caption"><span>🌿</span>{game.house?'Twoja farma rośnie!':'Zacznij od zebrania materiałów na domek.'}</div></section>
    <section className="quest-card"><div className="quest-heading"><div><span className="eyebrow">PRZYGODA 1</span><h2>Urządź swoją farmę</h2></div><div className="progress-ring">{done}<small>/6</small></div></div><div className="progress-track"><i style={{width:`${done/6*100}%`}}/></div><div className="quest-list">{chores.map(([label,complete],i)=><div className={`quest-row ${complete?'complete':''}`} key={label}><span className="check">{complete?'✓':i+1}</span><span>{label}</span>{complete&&<span className="done-label">GOTOWE</span>}</div>)}</div></section>
    <section className="actions-card"><div className="section-heading"><div><span className="eyebrow">CO ROBIMY?</span><h2>Twoje przygody</h2></div><span className="sparkle">✨</span></div><div className="action-grid"><button className="action action-green" onClick={()=>act('wood',2,'Zebrano 2 kawałki drewna!')}><span>🪓</span><b>Zbieraj drewno</b><small>+2 drewna</small></button><button className="action action-blue" onClick={()=>act('stone',2,'Udało się! +2 kamienie')}><span>⛏️</span><b>Kop kamienie</b><small>+2 kamienie</small></button><button className="action action-yellow" onClick={()=>act('carrots',1,'Zebrano marchewkę!')}><span>🌱</span><b>Zbieraj plony</b><small>+1 marchewka</small></button><button className="action action-pink" onClick={()=>setShowShop(true)}><span>🏪</span><b>Odwiedź sklepik</b><small>wymień skarby</small></button></div></section>
    <section className="build-card"><div className="section-heading"><div><span className="eyebrow">BUDUJ I ODKRYWAJ</span><h2>Następny krok</h2></div><span className="sparkle">🧰</span></div><div className="build-list"><div className={`build-row ${game.house?'built':''}`}><span className="build-emoji">🏠</span><div className="build-info"><b>{game.house?'Domek gotowy!':'Zbuduj mały domek'}</b><small>{game.house?'Możesz urządzić swoje podwórko.':'Potrzeba: 6 drewna · 5 kamieni'}</small></div><button disabled={game.house} onClick={buyHouse}>{game.house?'✓':'Zbuduj'}</button></div><div className={`build-row ${game.planted?'built':''}`}><span className="build-emoji">🥕</span><div className="build-info"><b>{game.planted?'Grządka marchewek':'Zasadź marchewki'}</b><small>{game.planted?(game.watered?'Marchewki urosły!':'Podlej, żeby wyrosły!'):'Potrzeba: 1 marchewka'}</small></div><button disabled={game.watered} onClick={game.planted?water:plant}>{game.watered?'✓':game.planted?'Podlej':'Zasadź'}</button></div><div className={`build-row ${game.hutch?'built':''}`}><span className="build-emoji">🛖</span><div className="build-info"><b>{game.hutch?'Zagroda gotowa!':'Zbuduj króliczą zagrodę'}</b><small>{game.hutch?'Bezpieczne miejsce dla uszatych gości.':'Potrzeba: 3 drewna · 3 monety'}</small></div><button disabled={game.hutch} onClick={buyHutch}>{game.hutch?'✓':'Zbuduj'}</button></div><div className={`build-row ${game.rabbits?'built':''}`}><span className="build-emoji">🐰</span><div className="build-info"><b>{game.rabbits?'Bezuch i Karmelka':'Poznaj króliczki'}</b><small>{game.rabbits?'Mniam! Marchewka poprawia humor.':'Zbuduj zagrodę, by je przywitać.'}</small></div><button disabled={game.rabbits>0} onClick={meetBunnies}>{game.rabbits?'♥':'Poznaj'}</button></div><div className={`build-row ${game.fed?'built':''}`}><span className="build-emoji">🥬</span><div className="build-info"><b>{game.fed?'Króliki najedzone!':'Nakarm króliczki'}</b><small>{game.fed?'Dostałaś 3 monety za wełnę!':'Potrzeba: 1 marchewka'}</small></div><button disabled={game.fed} onClick={feed}>{game.fed?'✓':'Nakarm'}</button></div></div></section>
    </>: <Village onToast={say} />}
    <footer><span>⌁</span> Każda wielka farma zaczyna się od małego ziarenka.<button onClick={reset}>Zacznij od nowa</button></footer>
    {toast&&<div className="toast" role="status">✨ {toast}</div>}
    {showShop&&<div className="modal-backdrop" onClick={()=>setShowShop(false)}><section className="shop-modal" role="dialog" aria-modal="true" aria-labelledby="shop-title" onClick={e=>e.stopPropagation()}><button className="close-modal" aria-label="Zamknij sklepik" onClick={()=>setShowShop(false)}>×</button><div className="modal-icon">🏪</div><span className="eyebrow">SKLEPIK POD KLAMERKĄ</span><h2 id="shop-title">Wymień swoje skarby</h2><p>Sprzedaj marchewki albo kup coś przydatnego na farmę.</p><div className="shop-offers"><div className="shop-offer"><span>🥕</span><div><b>Sprzedaj 3 marchewki</b><small>Dostaniesz 4 monety</small></div><button onClick={shopSell}>Sprzedaj</button></div><div className="shop-offer"><span>🌱</span><div><b>Kup paczkę nasion</b><small>2 monety → 2 marchewki</small></div><button onClick={shopSeeds}>Kup · 2 🪙</button></div><div className="shop-offer"><span>🧺</span><div><b>Pakiet budowniczego</b><small>5 monet → 2 drewna i 2 kamienie</small></div><button onClick={shopMaterials}>Kup · 5 🪙</button></div></div><div className="wallet">Masz teraz <b>🪙 {game.coins}</b> monet i <b>🥕 {game.carrots}</b> marchewki</div></section></div>}
    {showName&&<div className="modal-backdrop"><form className="name-modal" onSubmit={submitName}><div className="modal-icon">🌼</div><span className="eyebrow">NOWA PRZYGODA</span><h2>Wybierz swoją postać</h2><p>Kogo spotkamy na farmie?</p><div className="avatar-choices"><button type="button" className={newAvatar==='girl'?'chosen':''} onClick={()=>setNewAvatar('girl')}><span>👧🏻‍🌾</span><b>Dziewczynka</b></button><button type="button" className={newAvatar==='boy'?'chosen':''} onClick={()=>setNewAvatar('boy')}><span>👦🏻‍🌾</span><b>Chłopiec</b></button></div><label className="name-label" htmlFor="player-name">Jak ma na imię?</label><input autoFocus id="player-name" name="name" placeholder="Wpisz imię postaci" maxLength="16" required/><button className="enter-farm" type="submit">Wejdź na farmę <span>→</span></button><small>Postęp zapisuje się tylko na tym urządzeniu.</small></form></div>}
  </main>
}

createRoot(document.getElementById('root')).render(<App/>);
